services:
    laravel.mysql:
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
        volumes:
            - 'mysql_data:/var/lib/mysql'
        networks:
            - sail
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-apache
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        networks:
            - sail
        depends_on:
            - laravel.mysql
            

networks:
    sail:
        driver: bridge

volumes:
    mysql_data:
        driver: local